#!/usr/bin/env ansible-playbook

- name: Gather prerequisites 
  hosts: all
  gather_facts: True
  tasks:
    - group_by: key={{ ansible_distribution }}

- name: Install Ubuntu Packages
  hosts: Ubuntu
  become: True
  tasks:
    - apt: name=curl state=latest update_cache=true cache_valid_time=600

- name: Install CentOS Packages
  hosts: CentOS
  become: True
  tasks:
    - yum: name=curl state=latest

- name: Install Docker
  hosts: Ubuntu
  become: True
  tasks:
    - command: /usr/bin/curl --location --output /root/install-docker https://get.docker.com/
    - file: path=/root/install-docker owner=root group=root mode=0500
    - shell: /root/install-docker
    - file: path=/etc/systemd/system/docker.service.d state=directory mode=0755
    - copy: src=files/root-dir.conf dest=/etc/systemd/system/docker.service.d/root-dir.conf owner=root group=root mode=444 backup=no
    - user: name=vagrant groups=docker append=yes
#   - command: usermod -aG docker vagrant
#   - command: systemctl daemon-reload
    - systemd: state=restarted daemon_reload=yes name=docker
#   - command: service docker restart
#   - command: systemctl restart docker
    - command: docker run hello-world

- name: Install Docker Compose
  hosts: all
  become: True
  vars:
    version: 1.8.1
  tasks:
    - get_url: url=https://github.com/docker/compose/releases/download/{{ version }}/docker-compose-Linux-x86_64 dest=/usr/local/bin/docker-compose mode=0555
    - command: /usr/local/bin/docker-compose --version

- name: Install Docker Machine
  hosts: all
  become: True
  vars:
    version: 0.8.2
  tasks:
    - get_url: url=https://github.com/docker/machine/releases/download/v{{ version }}/docker-machine-Linux-x86_64 dest=/usr/local/bin/docker-machine mode=0555
    - command: /usr/local/bin/docker-machine --version
